import { Document, Packer, Paragraph, TextRun, AlignmentType } from "docx";
import { jsPDF } from "jspdf";

export interface DocBlock {
  type: 'h1' | 'h2' | 'h3' | 'p' | 'bullet' | 'numbered';
  text: string;
}

/**
 * Parses semantic HTML (generated by Mammoth from a DOCX) into structured document blocks.
 * Early returns on block elements prevent duplicate text reads.
 */
export function parseHtmlToBlocks(html: string): DocBlock[] {
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, "text/html");
  const blocks: DocBlock[] = [];

  const traverse = (node: Node) => {
    if (node.nodeType === Node.ELEMENT_NODE) {
      const el = node as HTMLElement;
      const tagName = el.tagName.toLowerCase();

      if (tagName === "h1" || tagName === "h2" || tagName === "h3" || tagName === "p" || tagName === "li") {
        let type: 'h1' | 'h2' | 'h3' | 'p' | 'bullet' | 'numbered' = 'p';
        if (tagName === "h1") type = "h1";
        else if (tagName === "h2") type = "h2";
        else if (tagName === "h3") type = "h3";
        else if (tagName === "li") {
          const parent = el.parentElement?.tagName.toLowerCase();
          type = parent === "ol" ? "numbered" : "bullet";
        }
        
        const text = el.textContent?.trim() || "";
        if (text) {
          blocks.push({ type, text });
        }
        return; // Stop traversing inside this block to prevent nested runs duplication
      }

      // If not a block element, traverse children
      for (let i = 0; i < el.childNodes.length; i++) {
        traverse(el.childNodes[i]);
      }
    }
  };

  traverse(doc.body);
  return blocks;
}

/**
 * Parses raw text line-by-line using heuristics to classify sections into structured document blocks.
 * Groups consecutive standard body lines into single paragraphs while keeping headings and list items separate.
 */
export function parseTextToBlocks(text: string): DocBlock[] {
  const normalized = text.replace(/\r\n/g, "\n");
  const lines = normalized.split("\n").map(l => l.trim()).filter(Boolean);
  const blocks: DocBlock[] = [];
  
  let currentParagraph = "";
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    
    const isBullet = /^[•\-*]\s+/.test(line);
    const isNumbered = /^\d+[\.\)]\s+/.test(line);
    
    // Header heuristic: short (< 100 chars), no ending sentence punctuation, starts with number or in all-caps
    const isHeader = line.length < 100 && 
                     !/[.!?]$/.test(line) && 
                     (line === line.toUpperCase() || /^\d+(\.\d+)*\s+[A-Z]/.test(line));
    
    if (isBullet || isNumbered || isHeader) {
      if (currentParagraph) {
        blocks.push({ type: "p", text: currentParagraph });
        currentParagraph = "";
      }
      
      if (isBullet) {
        blocks.push({ type: "bullet", text: line.replace(/^[•\-*]\s+/, "") });
      } else if (isNumbered) {
        blocks.push({ type: "numbered", text: line.replace(/^\d+[\.\)]\s+/, "") });
      } else {
        // Classify as h2 for standard section titles
        blocks.push({ type: "h2", text: line });
      }
    } else {
      if (currentParagraph) {
        currentParagraph += " " + line;
      } else {
        currentParagraph = line;
      }
    }
  }
  
  if (currentParagraph) {
    blocks.push({ type: "p", text: currentParagraph });
  }
  
  return blocks;
}

/**
 * Maps clean plain-text humanized output back to structured DocBlocks using original blocks as a template.
 */
export function mapParagraphsToBlocks(humanizedText: string, originalBlocks: DocBlock[]): DocBlock[] {
  const normalized = humanizedText.replace(/\r\n/g, "\n");
  
  // Split by double newlines first
  let paragraphs = normalized
    .split(/\n\n+/)
    .map(p => p.trim())
    .filter(Boolean);

  // Fallback: if LLM separated with single newlines and we expected multiple blocks
  if (paragraphs.length <= 1 && originalBlocks.length > 1 && normalized.includes('\n')) {
    paragraphs = normalized
      .split('\n')
      .map(p => p.trim())
      .filter(Boolean);
  }

  const resultBlocks: DocBlock[] = [];
  
  paragraphs.forEach((text, index) => {
    let type: 'h1' | 'h2' | 'h3' | 'p' | 'bullet' | 'numbered' = 'p';
    
    if (index < originalBlocks.length) {
      type = originalBlocks[index].type;
    } else {
      // Use the last block type as a fallback
      type = originalBlocks[originalBlocks.length - 1]?.type || 'p';
    }
    
    // Clean any accidentally leaked inline HTML/XML tags from LLM outputs
    const cleanText = text.replace(/<\/?[a-zA-Z0-9_]+>/g, "").trim();
    
    resultBlocks.push({ type, text: cleanText });
  });

  return resultBlocks;
}

/**
 * Compiles document blocks back into a Word (.docx) file with proper layout mappings.
 */
export async function generateDocxFromBlocks(blocks: DocBlock[]): Promise<Blob> {
  const children: any[] = [];
  let numberedIndex = 1;

  blocks.forEach(block => {
    if (block.type === 'h1') {
      numberedIndex = 1;
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: block.text,
              bold: true,
              size: 32, // 16pt
              font: "Calibri",
            }),
          ],
          spacing: { before: 280, after: 140 },
        })
      );
    } else if (block.type === 'h2') {
      numberedIndex = 1;
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: block.text,
              bold: true,
              size: 26, // 13pt
              font: "Calibri",
            }),
          ],
          spacing: { before: 240, after: 120 },
        })
      );
    } else if (block.type === 'h3') {
      numberedIndex = 1;
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: block.text,
              bold: true,
              size: 22, // 11pt
              font: "Calibri",
            }),
          ],
          spacing: { before: 200, after: 100 },
        })
      );
    } else if (block.type === 'bullet') {
      numberedIndex = 1;
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: block.text,
              size: 22, // 11pt
              font: "Calibri",
            }),
          ],
          bullet: {
            level: 0,
          },
          spacing: { after: 120 },
        })
      );
    } else if (block.type === 'numbered') {
      // Create a simulated list item with prefix to ensure consistent formatting in all readers
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `${numberedIndex}.  ${block.text}`,
              size: 22, // 11pt
              font: "Calibri",
            }),
          ],
          spacing: { after: 120 },
        })
      );
      numberedIndex++;
    } else {
      numberedIndex = 1;
      // Normal Body Paragraph
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: block.text,
              size: 22, // 11pt
              font: "Calibri",
            }),
          ],
          spacing: { after: 180, line: 360 }, // 1.5 line spacing
        })
      );
    }
  });

  const doc = new Document({
    sections: [
      {
        properties: {},
        children,
      },
    ],
  });

  return await Packer.toBlob(doc);
}

/**
 * Compiles document blocks back into a clean multi-page PDF document.
 */
export async function generatePdfFromBlocks(blocks: DocBlock[]): Promise<Blob> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxLineWidth = pageWidth - 2 * margin;

  let y = margin;
  let numberedIndex = 1;

  blocks.forEach(block => {
    let fontSize = 11;
    let isBold = false;
    let isItalic = false;
    let lineSpacing = 6;
    let paragraphSpacing = 4;
    let prefix = "";
    let indent = 0;

    if (block.type === 'h1') {
      fontSize = 16;
      isBold = true;
      paragraphSpacing = 6;
    } else if (block.type === 'h2') {
      fontSize = 13;
      isBold = true;
      paragraphSpacing = 5;
    } else if (block.type === 'h3') {
      fontSize = 11;
      isBold = true;
      paragraphSpacing = 4;
    } else if (block.type === 'bullet') {
      prefix = "•  ";
      indent = 6;
      paragraphSpacing = 3;
    } else if (block.type === 'numbered') {
      prefix = `${numberedIndex}. `;
      indent = 6;
      paragraphSpacing = 3;
      numberedIndex++;
    } else {
      fontSize = 11;
      paragraphSpacing = 5;
    }

    if (block.type !== 'numbered') {
      numberedIndex = 1;
    }

    doc.setFont("Helvetica", isBold ? "bold" : isItalic ? "italic" : "normal");
    doc.setFontSize(fontSize);
    doc.setTextColor(33, 33, 33);

    const currentMaxLineWidth = maxLineWidth - indent;
    const lines = doc.splitTextToSize(block.text, currentMaxLineWidth);

    lines.forEach((line, index) => {
      if (y > pageHeight - margin - 15) {
        doc.addPage();
        y = margin;
      }
      
      const currentX = margin + indent;
      if (index === 0 && prefix) {
        doc.text(prefix, margin, y);
      }
      doc.text(line, currentX, y);
      y += lineSpacing;
    });

    y += paragraphSpacing;
  });

  return doc.output("blob");
}

/**
 * Triggers browser-native file download for a given Blob.
 */
export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.style.display = "none";
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
