import { Document, Packer, Paragraph, TextRun, AlignmentType, Table, TableRow, TableCell, WidthType } from "docx";
import { jsPDF } from "jspdf";

export interface DocBlock {
  type: 'h1' | 'h2' | 'h3' | 'p' | 'bullet' | 'numbered' | 'table-cell';
  text: string;
  tableMetadata?: {
    tableId: string;
    rowIndex: number;
    colIndex: number;
    isHeader: boolean;
  };
}

/**
 * Parses semantic HTML (generated by Mammoth from a DOCX) into structured document blocks.
 * Extracts tables cell-by-cell with metadata to retain structural layouts.
 */
export function parseHtmlToBlocks(html: string): DocBlock[] {
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, "text/html");
  const blocks: DocBlock[] = [];

  const traverse = (node: Node) => {
    if (node.nodeType === Node.ELEMENT_NODE) {
      const el = node as HTMLElement;
      const tagName = el.tagName.toLowerCase();

      if (tagName === "table") {
        const tableId = `table_${Math.random().toString(36).substring(2, 9)}`;
        const rows = Array.from(el.querySelectorAll("tr"));
        rows.forEach((row, rowIndex) => {
          const cells = Array.from(row.querySelectorAll("td, th"));
          cells.forEach((cell, colIndex) => {
            blocks.push({
              type: "table-cell",
              text: cell.textContent?.trim() || "",
              tableMetadata: {
                tableId,
                rowIndex,
                colIndex,
                isHeader: cell.tagName.toLowerCase() === "th" || rowIndex === 0,
              }
            });
          });
        });
        return; // Skip traversing inside table element to prevent cell duplicate reads
      }

      if (tagName === "h1" || tagName === "h2" || tagName === "h3" || tagName === "p" || tagName === "li") {
        let type: 'h1' | 'h2' | 'h3' | 'p' | 'bullet' | 'numbered' | 'table-cell' = 'p';
        if (tagName === "h1") type = "h1";
        else if (tagName === "h2") type = "h2";
        else if (tagName === "h3") type = "h3";
        else if (tagName === "li") {
          const parent = el.parentElement?.tagName.toLowerCase();
          type = parent === "ol" ? "numbered" : "bullet";
        }
        
        const text = el.textContent?.trim() || "";
        if (text) {
          blocks.push({ type, text });
        }
        return;
      }

      for (let i = 0; i < el.childNodes.length; i++) {
        traverse(el.childNodes[i]);
      }
    }
  };

  traverse(doc.body);
  return blocks;
}

/**
 * Parses raw text line-by-line using heuristics to classify sections into structured document blocks.
 * Detects pipe-separated and tab-separated text as tables automatically.
 */
export function parseTextToBlocks(text: string): DocBlock[] {
  const normalized = text.replace(/\r\n/g, "\n");
  const lines = normalized.split("\n").map(l => l.trim());
  const blocks: DocBlock[] = [];
  
  let currentParagraph = "";
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    
    if (line === "") {
      if (currentParagraph) {
        blocks.push({ type: "p", text: currentParagraph });
        currentParagraph = "";
      }
      continue;
    }
    
    // Check if line represents a table row (contains pipes or multiple tabs)
    const isTableLine = line.includes("|") || (line.split(/\t/).length > 1);
    const isBullet = /^[•\-*]\s+/.test(line);
    const isNumbered = /^\d+[\.\)]\s+/.test(line);
    
    const isHeader = line.length < 100 && 
                     !/[.!?]$/.test(line) && 
                     (line === line.toUpperCase() || 
                      /^\d+(\.\d+)*\s+[A-Z]/.test(line) || 
                      /^[A-Z][a-z]+ \d+$/.test(line) || 
                      line.startsWith("Study ") || 
                      line.startsWith("Relevance "));
    
    if (isTableLine) {
      if (currentParagraph) {
        blocks.push({ type: "p", text: currentParagraph });
        currentParagraph = "";
      }
      
      const cells = line.split(/[|\t]/).map(c => c.trim()).filter(Boolean);
      if (cells.length > 0) {
        let tableId = "";
        let rowIndex = 0;
        const lastBlock = blocks[blocks.length - 1];
        if (lastBlock && lastBlock.type === "table-cell" && lastBlock.tableMetadata) {
          tableId = lastBlock.tableMetadata.tableId;
          rowIndex = lastBlock.tableMetadata.rowIndex + 1;
        } else {
          tableId = `table_${Math.random().toString(36).substring(2, 9)}`;
          rowIndex = 0;
        }
        
        cells.forEach((cellText, colIndex) => {
          blocks.push({
            type: "table-cell",
            text: cellText,
            tableMetadata: {
              tableId,
              rowIndex,
              colIndex,
              isHeader: rowIndex === 0,
            }
          });
        });
      }
      continue;
    }

    if (isBullet || isNumbered || isHeader) {
      if (currentParagraph) {
        blocks.push({ type: "p", text: currentParagraph });
        currentParagraph = "";
      }
      
      if (isBullet) {
        blocks.push({ type: "bullet", text: line.replace(/^[•\-*]\s+/, "") });
      } else if (isNumbered) {
        blocks.push({ type: "numbered", text: line.replace(/^\d+[\.\)]\s+/, "") });
      } else {
        blocks.push({ type: "h2", text: line });
      }
    } else {
      if (currentParagraph) {
        currentParagraph += " " + line;
      } else {
        currentParagraph = line;
      }
    }
  }
  
  if (currentParagraph) {
    blocks.push({ type: "p", text: currentParagraph });
  }
  
  return blocks;
}

/**
 * Maps clean plain-text humanized output back to structured DocBlocks using original blocks as a template.
 */
export function mapParagraphsToBlocks(humanizedText: string, originalBlocks: DocBlock[]): DocBlock[] {
  const normalized = humanizedText.replace(/\r\n/g, "\n");
  
  let paragraphs = normalized
    .split(/\n\n+/)
    .map(p => p.trim())
    .filter(Boolean);

  if (paragraphs.length <= 1 && originalBlocks.length > 1 && normalized.includes('\n')) {
    paragraphs = normalized
      .split('\n')
      .map(p => p.trim())
      .filter(Boolean);
  }

  const resultBlocks: DocBlock[] = [];
  
  paragraphs.forEach((text, index) => {
    let type: 'h1' | 'h2' | 'h3' | 'p' | 'bullet' | 'numbered' | 'table-cell' = 'p';
    let tableMetadata = undefined;
    
    if (index < originalBlocks.length) {
      type = originalBlocks[index].type;
      tableMetadata = originalBlocks[index].tableMetadata;
    } else {
      const lastBlock = originalBlocks[originalBlocks.length - 1];
      type = lastBlock?.type || 'p';
      tableMetadata = lastBlock?.tableMetadata;
    }
    
    const cleanText = text.replace(/<\/?[a-zA-Z0-9_]+>/g, "").trim();
    
    resultBlocks.push({ type, text: cleanText, tableMetadata });
  });

  return resultBlocks;
}

/**
 * Formats structured DocBlocks into a beautiful clean display string for UI textareas.
 * Groups table cells together row-by-row into Markdown table syntax representation.
 */
export function blocksToDisplayString(blocks: DocBlock[]): string {
  const parts: string[] = [];
  let numberedIndex = 1;

  for (let i = 0; i < blocks.length; i++) {
    const block = blocks[i];
    
    if (block.type === 'table-cell' && block.tableMetadata) {
      const tableId = block.tableMetadata.tableId;
      const tableBlocks: typeof block[] = [];
      while (i < blocks.length && blocks[i].type === 'table-cell' && blocks[i].tableMetadata?.tableId === tableId) {
        tableBlocks.push(blocks[i]);
        i++;
      }
      i--;

      // Group table cells by rowIndex
      const rowMap: { [key: number]: string[] } = {};
      tableBlocks.forEach(tb => {
        if (tb.tableMetadata) {
          if (!rowMap[tb.tableMetadata.rowIndex]) {
            rowMap[tb.tableMetadata.rowIndex] = [];
          }
          rowMap[tb.tableMetadata.rowIndex].push(tb.text);
        }
      });

      // Format row arrays into pipe syntax lines
      const tableLines: string[] = [];
      Object.keys(rowMap).sort((a, b) => Number(a) - Number(b)).forEach(r => {
        const rowCells = rowMap[Number(r)];
        tableLines.push(`| ${rowCells.join(' | ')} |`);
      });

      parts.push(tableLines.join('\n'));
      numberedIndex = 1;
    } else if (block.type === 'h1') {
      parts.push(block.text);
      numberedIndex = 1;
    } else if (block.type === 'h2') {
      parts.push(block.text);
      numberedIndex = 1;
    } else if (block.type === 'h3') {
      parts.push(block.text);
      numberedIndex = 1;
    } else if (block.type === 'bullet') {
      parts.push(`• ${block.text}`);
      numberedIndex = 1;
    } else if (block.type === 'numbered') {
      parts.push(`${numberedIndex}. ${block.text}`);
      numberedIndex++;
    } else {
      parts.push(block.text);
      numberedIndex = 1;
    }
  }

  return parts.join('\n\n');
}

/**
 * Generates a DOCX Table element from a 2D string grid.
 */
function createDocxTable(grid: string[][]): Table {
  return new Table({
    rows: grid.map((row, rIndex) => {
      const isHeader = rIndex === 0;
      return new TableRow({
        children: row.map((cellText) => {
          return new TableCell({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: cellText,
                    bold: isHeader,
                    size: 22, // 11pt
                    font: "Calibri",
                  })
                ],
                spacing: { before: 80, after: 80 },
              })
            ],
            shading: isHeader ? { fill: "F0F4F8" } : undefined, // Header tint bg
            margins: { top: 100, bottom: 100, left: 100, right: 100 },
          });
        })
      });
    }),
    width: {
      size: 100,
      type: WidthType.PERCENTAGE,
    }
  });
}

/**
 * Compiles document blocks back into a Word (.docx) file with proper layout mappings, including tables.
 */
export async function generateDocxFromBlocks(blocks: DocBlock[]): Promise<Blob> {
  const children: any[] = [];
  let numberedIndex = 1;

  for (let i = 0; i < blocks.length; i++) {
    const block = blocks[i];

    if (block.type === 'table-cell' && block.tableMetadata) {
      const tableId = block.tableMetadata.tableId;
      const tableBlocks: typeof block[] = [];
      while (i < blocks.length && blocks[i].type === 'table-cell' && blocks[i].tableMetadata?.tableId === tableId) {
        tableBlocks.push(blocks[i]);
        i++;
      }
      i--;

      let maxRow = 0;
      let maxCol = 0;
      tableBlocks.forEach(tb => {
        if (tb.tableMetadata) {
          if (tb.tableMetadata.rowIndex > maxRow) maxRow = tb.tableMetadata.rowIndex;
          if (tb.tableMetadata.colIndex > maxCol) maxCol = tb.tableMetadata.colIndex;
        }
      });

      const grid: string[][] = Array.from({ length: maxRow + 1 }, () => Array(maxCol + 1).fill(""));
      tableBlocks.forEach(tb => {
        if (tb.tableMetadata) {
          grid[tb.tableMetadata.rowIndex][tb.tableMetadata.colIndex] = tb.text;
        }
      });

      children.push(createDocxTable(grid));
      numberedIndex = 1;
    } else if (block.type === 'h1') {
      numberedIndex = 1;
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: block.text,
              bold: true,
              size: 32,
              font: "Calibri",
            }),
          ],
          spacing: { before: 280, after: 140 },
        })
      );
    } else if (block.type === 'h2') {
      numberedIndex = 1;
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: block.text,
              bold: true,
              size: 26,
              font: "Calibri",
            }),
          ],
          spacing: { before: 240, after: 120 },
        })
      );
    } else if (block.type === 'h3') {
      numberedIndex = 1;
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: block.text,
              bold: true,
              size: 22,
              font: "Calibri",
            }),
          ],
          spacing: { before: 200, after: 100 },
        })
      );
    } else if (block.type === 'bullet') {
      numberedIndex = 1;
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: block.text,
              size: 22,
              font: "Calibri",
            }),
          ],
          bullet: {
            level: 0,
          },
          spacing: { after: 120 },
        })
      );
    } else if (block.type === 'numbered') {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `${numberedIndex}.  ${block.text}`,
              size: 22,
              font: "Calibri",
            }),
          ],
          spacing: { after: 120 },
        })
      );
      numberedIndex++;
    } else {
      numberedIndex = 1;
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: block.text,
              size: 22,
              font: "Calibri",
            }),
          ],
          spacing: { after: 180, line: 360 },
        })
      );
    }
  }

  const doc = new Document({
    sections: [
      {
        properties: {},
        children,
      },
    ],
  });

  return await Packer.toBlob(doc);
}

/**
 * Draws a grid table in jsPDF with proper padding, header shading, cell alignments and word wraps.
 */
function drawPdfTable(doc: jsPDF, grid: string[][], y: number, margin: number, pageWidth: number, pageHeight: number, maxLineWidth: number): number {
  const colCount = grid[0]?.length || 1;
  const colWidth = maxLineWidth / colCount;
  const cellPadding = 3;
  let currentY = y;

  grid.forEach((row, rIndex) => {
    const isHeader = rIndex === 0;
    
    let maxLines = 1;
    row.forEach(cellText => {
      doc.setFontSize(10);
      doc.setFont("Helvetica", isHeader ? "bold" : "normal");
      const lines = doc.splitTextToSize(cellText, colWidth - 2 * cellPadding);
      if (lines.length > maxLines) {
        maxLines = lines.length;
      }
    });

    const rowHeight = maxLines * 5 + 6;

    if (currentY + rowHeight > pageHeight - margin - 10) {
      doc.addPage();
      currentY = margin;
    }

    row.forEach((cellText, cIndex) => {
      const cellX = margin + cIndex * colWidth;
      
      if (isHeader) {
        doc.setFillColor(240, 244, 248);
        doc.rect(cellX, currentY, colWidth, rowHeight, "F");
      }
      
      doc.setDrawColor(200, 200, 200);
      doc.rect(cellX, currentY, colWidth, rowHeight, "D");

      doc.setFont("Helvetica", isHeader ? "bold" : "normal");
      doc.setFontSize(9);
      doc.setTextColor(33, 33, 33);
      
      const textX = cellX + cellPadding;
      const lines = doc.splitTextToSize(cellText, colWidth - 2 * cellPadding);
      lines.forEach((line, lineIdx) => {
        const textY = currentY + cellPadding + 4 + (lineIdx * 5);
        doc.text(line, textX, textY);
      });
    });

    currentY += rowHeight;
  });

  return currentY;
}

/**
 * Compiles document blocks back into a clean multi-page PDF document, rendering tables correctly.
 */
export async function generatePdfFromBlocks(blocks: DocBlock[]): Promise<Blob> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxLineWidth = pageWidth - 2 * margin;

  let y = margin;
  let numberedIndex = 1;

  for (let i = 0; i < blocks.length; i++) {
    const block = blocks[i];

    if (block.type === 'table-cell' && block.tableMetadata) {
      const tableId = block.tableMetadata.tableId;
      const tableBlocks: typeof block[] = [];
      while (i < blocks.length && blocks[i].type === 'table-cell' && blocks[i].tableMetadata?.tableId === tableId) {
        tableBlocks.push(blocks[i]);
        i++;
      }
      i--;

      let maxRow = 0;
      let maxCol = 0;
      tableBlocks.forEach(tb => {
        if (tb.tableMetadata) {
          if (tb.tableMetadata.rowIndex > maxRow) maxRow = tb.tableMetadata.rowIndex;
          if (tb.tableMetadata.colIndex > maxCol) maxCol = tb.tableMetadata.colIndex;
        }
      });

      const grid: string[][] = Array.from({ length: maxRow + 1 }, () => Array(maxCol + 1).fill(""));
      tableBlocks.forEach(tb => {
        if (tb.tableMetadata) {
          grid[tb.tableMetadata.rowIndex][tb.tableMetadata.colIndex] = tb.text;
        }
      });

      y = drawPdfTable(doc, grid, y, margin, pageWidth, pageHeight, maxLineWidth);
      numberedIndex = 1;
    } else {
      let fontSize = 11;
      let isBold = false;
      let isItalic = false;
      let lineSpacing = 6;
      let paragraphSpacing = 4;
      let prefix = "";
      let indent = 0;

      if (block.type === 'h1') {
        fontSize = 16;
        isBold = true;
        paragraphSpacing = 6;
      } else if (block.type === 'h2') {
        fontSize = 13;
        isBold = true;
        paragraphSpacing = 5;
      } else if (block.type === 'h3') {
        fontSize = 11;
        isBold = true;
        paragraphSpacing = 4;
      } else if (block.type === 'bullet') {
        prefix = "•  ";
        indent = 6;
        paragraphSpacing = 3;
      } else if (block.type === 'numbered') {
        prefix = `${numberedIndex}. `;
        indent = 6;
        paragraphSpacing = 3;
        numberedIndex++;
      } else {
        fontSize = 11;
        paragraphSpacing = 5;
      }

      if (block.type !== 'numbered') {
        numberedIndex = 1;
      }

      doc.setFont("Helvetica", isBold ? "bold" : isItalic ? "italic" : "normal");
      doc.setFontSize(fontSize);
      doc.setTextColor(33, 33, 33);

      const currentMaxLineWidth = maxLineWidth - indent;
      const lines = doc.splitTextToSize(block.text, currentMaxLineWidth);

      lines.forEach((line, index) => {
        if (y > pageHeight - margin - 15) {
          doc.addPage();
          y = margin;
        }
        
        const currentX = margin + indent;
        if (index === 0 && prefix) {
          doc.text(prefix, margin, y);
        }
        doc.text(line, currentX, y);
        y += lineSpacing;
      });

      y += paragraphSpacing;
    }
  }

  return doc.output("blob");
}

/**
 * Triggers browser-native file download for a given Blob.
 */
export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.style.display = "none";
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
