import { useState } from "react";
import { Layout } from "@/components/layout/Layout";
import { Button } from "@/components/ui/button";
import { TextAreaBox } from "@/components/ui/TextAreaBox";
import { Search, Loader2, Eye, AlertCircle, ScanText, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { CircularGauge } from "@/components/ui/CircularGauge";
import { API_BASE_URL } from "@/config";
import { motion, AnimatePresence } from "framer-motion";

interface SentenceBreakdown {
  text: string;
  score: number;
}

interface DetectorResult {
  aiScore: number;
  humanScore: number;
  sentenceBreakdown: SentenceBreakdown[];
  analysis?: {
    patternScore: number;
    burstiScore: number;
    uniformityScore: number;
    punctuationScore: number;
    transitionScore: number;
  };
}

export default function AIDetector() {
  const [inputText, setInputText] = useState("");
  const [isProcessing, setIsProcessing] = useState(false);
  const [result, setResult] = useState<DetectorResult | null>(null);

  const charCount = inputText.length;
  const maxChars = 100000;

  const handleCheck = async () => {
    if (!inputText.trim()) {
      toast.error("Please enter some text to analyze");
      return;
    }

    if (charCount > maxChars) {
      toast.error(`Text exceeds maximum limit of ${maxChars.toLocaleString()} characters`);
      return;
    }

    setIsProcessing(true);

    try {
      const response = await fetch(`${API_BASE_URL}/api/ai-detector`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: inputText }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        const message = errorData.error || "Analysis failed";
        if (message.includes("429") || message.includes("rate limit")) {
          toast.error("Rate limit reached. Please wait a few seconds and try again.");
        } else {
          throw new Error(message);
        }
        return;
      }

      const data = await response.json();

      if (data?.error) {
        toast.error(data.error);
        return;
      }

      setResult(data as DetectorResult);
      toast.success("Analysis complete");
    } catch (error) {
      console.error("Detector error:", error);
      toast.error("Failed to analyze text. Please try again.");
    } finally {
      setIsProcessing(false);
    }
  };

  const getSummaryMessage = (score: number) => {
    if (score < 10) return "Your text is authentically human-written. Keep it up!";
    if (score < 30) return "Your text appears to be mostly human-written with minor patterns.";
    if (score < 70) return "Your text contains mixed signals, with some parts generated by AI/GPT.";
    if (score < 90) return "Your text is likely AI-generated. Consider humanizing it.";
    return "Your text is almost certainly AI/GPT generated.";
  };

  const getSentenceScoreColor = (score: number) => {
    if (score <= 20) return "bg-green-500 shadow-[0_0_10px_rgba(34,197,94,0.5)]";
    if (score <= 50) return "bg-yellow-500 shadow-[0_0_10px_rgba(234,179,8,0.5)]";
    return "bg-red-500 shadow-[0_0_10px_rgba(239,68,68,0.5)]";
  };

  const getSentenceBgColor = (score: number) => {
    if (score <= 20) return "bg-green-50/50 border-green-200/50 dark:bg-green-950/20 dark:border-green-900/30";
    if (score <= 50) return "bg-yellow-50/50 border-yellow-200/50 dark:bg-yellow-950/20 dark:border-yellow-900/30";
    return "bg-red-50/50 border-red-200/50 dark:bg-red-950/20 dark:border-red-900/30";
  };

  return (
    <Layout>
      <div className="relative min-h-[calc(100vh-4rem)] py-8 md:py-16 overflow-hidden">
        {/* Background Gradients */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none z-0">
          <div className="absolute -top-40 -right-40 w-[600px] h-[600px] rounded-full bg-accent/10 blur-[120px] mix-blend-screen" />
          <div className="absolute top-1/2 -left-40 w-[500px] h-[500px] rounded-full bg-primary/10 blur-[100px] mix-blend-screen" />
        </div>

        <div className="container relative z-10 max-w-5xl mx-auto px-4">
          {/* Header */}
          <motion.div 
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center mb-12"
          >
            <div className="inline-flex items-center justify-center p-3 bg-primary/10 rounded-2xl mb-4">
              <ScanText className="h-8 w-8 text-primary" />
            </div>
            <h1 className="text-4xl md:text-5xl font-extrabold text-foreground mb-4 tracking-tight">
              AI Content <span className="gradient-primary-text">Detector</span>
            </h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Deep semantic analysis to detect AI-generated content down to the specific sentence level.
            </p>
          </motion.div>

          {/* Input Section */}
          <motion.div 
            initial={{ opacity: 0, scale: 0.98 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="mb-12 relative"
          >
            <div className="relative bg-card/40 backdrop-blur-xl border border-white/10 dark:border-white/5 rounded-3xl p-6 shadow-card-lg">
              <div className="relative rounded-2xl overflow-hidden group">
                <TextAreaBox
                  label="Text to Analyze"
                  value={inputText}
                  onChange={setInputText}
                  placeholder="Paste your text here to check for AI-generated content..."
                  maxHeight="350px"
                  className="bg-background/50 border-none rounded-2xl transition-all"
                />
                
                {/* Scanning Overlay Animation */}
                <AnimatePresence>
                  {isProcessing && (
                    <motion.div 
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      className="absolute inset-0 z-20 pointer-events-none"
                    >
                      <motion.div
                        animate={{ y: ["-10%", "110%"] }}
                        transition={{ duration: 2.5, ease: "linear", repeat: Infinity }}
                        className="absolute inset-x-0 h-1 bg-gradient-to-r from-transparent via-primary to-transparent shadow-[0_0_15px_hsl(var(--primary))]"
                      />
                      <div className="absolute inset-0 bg-primary/5 animate-pulse" />
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>

              <div className="flex flex-col sm:flex-row items-center justify-between mt-6 gap-4">
                <span className="text-sm font-medium text-muted-foreground bg-background/50 px-4 py-2 rounded-xl border border-border/50">
                  <span className={charCount > maxChars ? "text-destructive" : ""}>
                    {charCount.toLocaleString()}
                  </span>{" "}
                  / {maxChars.toLocaleString()} chars
                </span>
                <Button
                  variant="gradient"
                  size="xl"
                  onClick={handleCheck}
                  disabled={isProcessing || !inputText.trim()}
                  className="w-full sm:w-auto rounded-xl shadow-lg relative overflow-hidden group"
                >
                  <div className="absolute inset-0 bg-white/20 translate-y-full group-hover:translate-y-0 transition-transform duration-300 ease-out" />
                  <span className="relative flex items-center justify-center gap-2">
                    {isProcessing ? (
                      <Loader2 className="h-5 w-5 animate-spin" />
                    ) : (
                      <Sparkles className="h-5 w-5" />
                    )}
                    Analyze Text
                  </span>
                </Button>
              </div>
            </div>
          </motion.div>

          {/* Analysis Results */}
          <AnimatePresence>
            {result && (
              <motion.div 
                initial={{ opacity: 0, y: 40 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, type: "spring", bounce: 0.4 }}
                className="space-y-8"
              >
                {/* Analysis Summary - Two Column Layout */}
                <div className="grid md:grid-cols-2 gap-6">
                  {/* Left: Circular Gauge */}
                  <div className="bg-card/40 backdrop-blur-xl rounded-[2rem] border border-white/10 p-8 shadow-card-lg flex flex-col items-center justify-center relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-32 h-32 bg-primary/5 rounded-full blur-3xl" />
                    <CircularGauge score={result.aiScore} />
                  </div>

                  {/* Right: Analysis Summary */}
                  <div className="bg-card/40 backdrop-blur-xl rounded-[2rem] border border-white/10 p-8 shadow-card-lg relative overflow-hidden">
                    <div className="absolute bottom-0 right-0 w-40 h-40 bg-accent/5 rounded-full blur-3xl" />
                    <h3 className="text-2xl font-bold text-foreground mb-6 flex items-center gap-2">
                      <AlertCircle className="h-6 w-6 text-primary" />
                      Analysis Summary
                    </h3>

                    <div className="space-y-6 relative z-10">
                      {/* AI Generated Bar */}
                      <div className="group">
                        <div className="flex justify-between text-sm mb-2">
                          <span className="text-foreground font-semibold">AI Generated Content</span>
                          <span className="text-red-500 font-bold">{result.aiScore.toFixed(1)}%</span>
                        </div>
                        <div className="h-4 bg-muted/50 rounded-full overflow-hidden border border-border/50">
                          <motion.div
                            initial={{ width: 0 }}
                            animate={{ width: `${result.aiScore}%` }}
                            transition={{ duration: 1, ease: "easeOut" }}
                            className="h-full bg-gradient-to-r from-red-600 to-red-400 rounded-full relative"
                          >
                            <div className="absolute inset-0 bg-white/20 animate-pulse" />
                          </motion.div>
                        </div>
                      </div>

                      {/* Human Written Bar */}
                      <div className="group">
                        <div className="flex justify-between text-sm mb-2">
                          <span className="text-foreground font-semibold">Human Written Content</span>
                          <span className="text-green-500 font-bold">{result.humanScore.toFixed(1)}%</span>
                        </div>
                        <div className="h-4 bg-muted/50 rounded-full overflow-hidden border border-border/50">
                          <motion.div
                            initial={{ width: 0 }}
                            animate={{ width: `${result.humanScore}%` }}
                            transition={{ duration: 1, ease: "easeOut" }}
                            className="h-full bg-gradient-to-r from-green-600 to-green-400 rounded-full relative"
                          >
                            <div className="absolute inset-0 bg-white/20 animate-pulse" />
                          </motion.div>
                        </div>
                      </div>

                      {/* Summary Message */}
                      <motion.div 
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ delay: 0.5 }}
                        className={cn(
                          "flex items-start gap-3 p-4 rounded-xl mt-6 border shadow-sm",
                          result.aiScore > 50 
                            ? "bg-red-50/50 border-red-200 dark:bg-red-950/20 dark:border-red-900/30" 
                            : "bg-green-50/50 border-green-200 dark:bg-green-950/20 dark:border-green-900/30"
                        )}
                      >
                        <Sparkles className={cn(
                          "h-5 w-5 mt-0.5 flex-shrink-0",
                          result.aiScore > 50 ? "text-red-500" : "text-green-500"
                        )} />
                        <p className={cn(
                          "text-sm font-medium leading-relaxed",
                          result.aiScore > 50 ? "text-red-800 dark:text-red-200" : "text-green-800 dark:text-green-200"
                        )}>
                          {getSummaryMessage(result.aiScore)}
                        </p>
                      </motion.div>
                    </div>
                  </div>
                </div>

                {/* Sentence-Level Analysis */}
                {result.sentenceBreakdown && result.sentenceBreakdown.length > 0 && (
                  <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2 }}
                    className="bg-card/40 backdrop-blur-xl rounded-[2rem] border border-white/10 p-8 shadow-card-lg"
                  >
                    <div className="flex items-center gap-3 mb-6 border-b border-border/50 pb-4">
                      <div className="p-2 bg-primary/10 rounded-lg">
                        <Eye className="h-5 w-5 text-primary" />
                      </div>
                      <h3 className="text-xl font-bold text-foreground tracking-tight">
                        Sentence-Level Breakdown
                      </h3>
                    </div>

                    <div className="space-y-4 max-h-[500px] overflow-y-auto pr-3 scrollbar-thin">
                      {result.sentenceBreakdown.map((sentence, index) => (
                        <motion.div
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: Math.min(index * 0.05, 1) }}
                          key={index}
                          whileHover={{ y: -2, scale: 1.005 }}
                          className={cn(
                            "p-5 rounded-2xl border transition-all shadow-sm",
                            getSentenceBgColor(sentence.score)
                          )}
                        >
                          <div className="flex flex-col sm:flex-row items-start justify-between gap-4">
                            <p className="text-foreground/90 text-[15px] flex-1 leading-relaxed font-medium">
                              {sentence.text}
                            </p>
                            <div className="flex-shrink-0">
                              <span
                                className={cn(
                                  "inline-flex items-center justify-center px-4 py-1.5 rounded-full text-xs font-bold text-white transition-shadow duration-300",
                                  getSentenceScoreColor(sentence.score)
                                )}
                              >
                                {sentence.score.toFixed(0)}% AI
                              </span>
                            </div>
                          </div>
                        </motion.div>
                      ))}
                    </div>
                  </motion.div>
                )}
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </Layout>
  );
}
